/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkWelearnRouteImport } from './routes/work.welearn'
import { Route as WorkUnifeedRouteImport } from './routes/work.unifeed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWelearnRoute = WorkWelearnRouteImport.update({
  id: '/work/welearn',
  path: '/work/welearn',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkUnifeedRoute = WorkUnifeedRouteImport.update({
  id: '/work/unifeed',
  path: '/work/unifeed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/unifeed': typeof WorkUnifeedRoute
  '/work/welearn': typeof WorkWelearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/unifeed': typeof WorkUnifeedRoute
  '/work/welearn': typeof WorkWelearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/unifeed': typeof WorkUnifeedRoute
  '/work/welearn': typeof WorkWelearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/unifeed' | '/work/welearn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/unifeed' | '/work/welearn'
  id: '__root__' | '/' | '/work/unifeed' | '/work/welearn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkUnifeedRoute: typeof WorkUnifeedRoute
  WorkWelearnRoute: typeof WorkWelearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/welearn': {
      id: '/work/welearn'
      path: '/work/welearn'
      fullPath: '/work/welearn'
      preLoaderRoute: typeof WorkWelearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/unifeed': {
      id: '/work/unifeed'
      path: '/work/unifeed'
      fullPath: '/work/unifeed'
      preLoaderRoute: typeof WorkUnifeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkUnifeedRoute: WorkUnifeedRoute,
  WorkWelearnRoute: WorkWelearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
